# Generated by Django 2.0.4 on 2018-04-13 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateTimeField(verbose_name='Data da Entrada')),
                ('emission_date', models.DateTimeField(verbose_name='Data de Emissão')),
                ('register_date', models.DateTimeField(verbose_name='Data de Registro')),
                ('invoice', models.CharField(max_length=100, verbose_name='NumNota')),
                ('series', models.CharField(max_length=100, verbose_name='Série')),
                ('user', models.CharField(max_length=100, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Entrada',
                'verbose_name_plural': 'Entradas',
            },
        ),
        migrations.CreateModel(
            name='EntryItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Quantidade')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço Base')),
                ('discount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Desconto')),
                ('addition', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Acréscimo')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse.Entry', verbose_name='Entrada')),
            ],
            options={
                'verbose_name': 'Item de Entrada',
                'verbose_name_plural': 'Itens de Entrada',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100, verbose_name='Descrição')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço')),
                ('quantity', models.IntegerField(verbose_name='Quantidade')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('cnpj', models.CharField(max_length=100, verbose_name='CNPJ')),
                ('zip_code', models.CharField(max_length=100, verbose_name='CEP')),
                ('address', models.CharField(max_length=100, verbose_name='Logradouro')),
                ('neighborhood', models.CharField(max_length=100, verbose_name='Bairro')),
                ('city', models.CharField(max_length=100, verbose_name='Cidade')),
                ('state', models.CharField(max_length=100, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Fornecedor',
                'verbose_name_plural': 'Fornecedores',
            },
        ),
        migrations.AddField(
            model_name='entryitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse.Product', verbose_name='Produto'),
        ),
        migrations.AddField(
            model_name='entry',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse.Provider', verbose_name='Fornecedor'),
        ),
    ]
