# Generated by Django 2.0.4 on 2018-04-13 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entry_provider', to='warehouse.Provider', verbose_name='Fornecedor'),
        ),
        migrations.AlterField(
            model_name='entryitem',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entryitem_entry', to='warehouse.Entry', verbose_name='Entrada'),
        ),
        migrations.AlterField(
            model_name='entryitem',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preço'),
        ),
        migrations.AlterField(
            model_name='entryitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eentryitem_product', to='warehouse.Product', verbose_name='Produto'),
        ),
    ]
